sudo: required
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
# command to install dependencies
#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq g++-7
#  - export CC=gcc-7
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
install:
  - pip install -q -r requirements.txt
  - pip install -q tensorflow
  - pip install -q pytest-xdist
  - pip install -q torch
  - pip install -q torchvision
  - pip install -q cppyy
# command to run tests
script: PYTHONPATH=src python3 -m pytest --cache-clear --ignore=src/spn/tests/test_tree_viz.py --ignore=src/spn/tests/test_cpp.py src/spn/tests/
#python3 -m unittest discover src/spn
